<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\FinTech.BuildingBlocks.Web\FinTech.BuildingBlocks.Web.csproj" />
    <ProjectReference Include="..\..\Modules\Ledger\FinTech.Modules.Ledger.Presentation\FinTech.Modules.Ledger.Presentation.csproj" />
    <ProjectReference Include="..\..\Modules\Ledger\FinTech.Modules.Ledger.Infrastructure\FinTech.Modules.Ledger.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
