<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FinTech.Modules.Ledger.Application\FinTech.Modules.Ledger.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\FinTech.BuildingBlocks.Web\FinTech.BuildingBlocks.Web.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
